---

# Application settings.
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements-production.txt"


# Django environment variables.
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_CONFIGURATION: "{{ django_configuration }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  DJANGO_MEDIA_ROOT: "{{ django_media_root }}"
  DJANGO_STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_URL: "postgres://{{ db_user }}:{{ db_password }}@{{ db_host }}/{{ db_name }}"
  DATABASE_NAME: "{{ db_name }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_HOST: "{{ db_host }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  CACHE_URL: "pymemcached://127.0.0.1:11211?key_prefix=fragdenstaat&timeout=3600"
  DJANGO_CELERY_BROKER_URL: "{{ celery_broker_url }}"
  DJANGO_EMAIL_HOST: "{{ email_host }}"
  DJANGO_EMAIL_HOST_USER: "{{ email_host_user }}"
  DJANGO_EMAIL_HOST_PASSWORD: "{{ email_host_password }}"
  DJANGO_FOI_EMAIL_HOST: "{{ foi_email_host }}"
  DJANGO_FOI_EMAIL_HOST_USER: "{{ foi_email_host_user }}"
  DJANGO_FOI_EMAIL_HOST_PASSWORD: "{{ foi_email_host_password }}"
  DJANGO_FOI_EMAIL_ACCOUNT_PASSWORD: "{{ foi_email_host_password }}"
  DJANGO_FOI_EMAIL_HOST_IMAP: "{{ foi_email_host }}"
  DJANGO_FOI_EMAIL_ACCOUNT_NAME: "{{ foi_email_host_user }}"
  DJANGO_BOUNCE_EMAIL_HOST_IMAP: "{{ bounce_email_host }}"
  DJANGO_BOUNCE_EMAIL_ACCOUNT_NAME: "{{ bounce_email_host_user }}"
  DJANGO_BOUNCE_EMAIL_ACCOUNT_PASSWORD: "{{ bounce_email_host_password }}"
  DJANGO_GEOIP_PATH: "{{ django_geoip_path }}"
  DJANGO_LOG_DIR: "{{ application_log_dir }}"
  DJANGO_SECRET_URL_ADMIN: "{{ django_secret_url_admin }}"
  DJANGO_SENTRY_DSN: "{{ django_sentry_dsn }}"
  YELP_API_KEY: "{{ yelp_api_key }}"
  MAPBOX_API_KEY: "{{ mapbox_api_key }}"
  FOURSQUARE_API_KEY: "{{ foursquare_api_key }}"
  GOOGLE_PLACES_API_KEY: "{{ google_places_api_key }}"
  HERE_GEOCODE_API_KEY: "{{ here_geocode_api_key }}"
  TWILIO_ACCOUNT_SID: "{{ twilio_account_sid }}"
  TWILIO_AUTH_TOKEN: "{{ twilio_auth_token }}"
  TWILIO_FROM_NUMBER: "{{ twilio_from_number }}"
  DJANGO_TESSERACT_DATA_PATH: "{{ tesseract_data_path }}"
